name: oggm_env_gungnir
channels:
  - conda-forge
dependencies:
  - bottleneck
  - cartopy
  - configobj
  - dask
  - geopandas
  - ipykernel
  - matplotlib
  - motionless
  - netcdf4
  - numpy<2.0
  - pandas
  - Pillow
  - pip
  - pyproj
  - pytables
  - pytest
  - python<3.12
  - rasterio
  - rioxarray
  - salem
  - scikit-image
  - scipy
  - seaborn
  - shapely
  - xarray
  - pip:
    - joblib
    - progressbar2
    - git+https://github.com/OGGM/pytest-mpl
    - git+https://github.com/OGGM/massbalance-sandbox
    - oggm
    - -e ./gungnir