name: oggm_env_gungnir
channels:
  - conda-forge
dependencies:
  - bottleneck
  - cartopy
  - configobj
  - dask
  - geopandas
  - ipykernel
  - matplotlib
  - motionless
  - netcdf4
  - numpy<2.0
  - pandas
  - Pillow
  - pip
  - pyproj
  - pytables
  - pytest
  - pytest-cov
  - python=3.10
  - rasterio
  - rioxarray
  - salem
  - scikit-image
  - scipy
  - seaborn
  - shapely
  - xarray
  - cdsapi
  - pip:
    - joblib
    - progressbar2
    - git+https://github.com/OGGM/pytest-mpl@ae429213fd4684ed52927cb4abc7930822f4a0e2
    - git+https://github.com/OGGM/massbalance-sandbox@947e7fcda103b2861e70d506d3ad6404e23de22d
    - oggm==1.6.3
    - -e ./gungnir
