name: oggm_env_gungnir
channels:
  - conda-forge
dependencies:
  - bottleneck
  - cartopy
  - configobj
  - dask
  - geopandas=1.1.4
  - ipykernel
  - libgdal-core=3.12.3
  - matplotlib
  - motionless
  - netcdf4=1.7.4
  - numpy=1.26.4
  - pandas=3.0.5
  - Pillow
  - pip
  - pyproj
  - pytables=3.11.1
  - pytest
  - pytest-cov
  - python<3.12
  - rasterio=1.4.4
  - rioxarray
  - salem=0.3.11
  - scikit-image=0.26.0
  - scipy
  - seaborn
  - shapely=2.1.2
  - xarray
  - cdsapi
  - pip:
    - joblib
    - progressbar2
    - git+https://github.com/OGGM/pytest-mpl@ae429213fd4684ed52927cb4abc7930822f4a0e2
    - git+https://github.com/OGGM/massbalance-sandbox@947e7fcda103b2861e70d506d3ad6404e23de22d
    - oggm==1.6.3
    - -e ./gungnir
