name: Run Unit Test via Pytest

on: [push]

jobs:
  build:
    runs-on: ubuntu-24.04 # Force ubuntu version since hash is version dependent
    strategy:
      matrix:
        python-version: ["3.10"]

    steps:
      - uses: actions/checkout@v4
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install environment
        uses: conda-incubator/setup-miniconda@v2
        with:
          miniconda-version: 'latest'
          channels: conda-forge
          channel-priority: true
          auto-update-conda: false
          auto-activate-base: false
          environment-file: environment.yml
      - name: Run tests
        shell: bash -l {0}
        run: |
          pytest -v -s
